export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  ADMIN_NAVIGATOR: 'AdminNavigator',
  DASHBOARD: 'Dashboard',
  PRODUCT_NAVIGATOR: 'Products',
  PRODUCTS: 'Products Screen',
  ADD_NEW_PRODUCT: 'Add New Product',
  UPDATE_PRODUCT: 'Update Product',
  ALL_PRODUCTS: 'All Products',
  ADD_STOCK: 'Add Stock',
  ADJUST_STOCK: 'Adjust Stock',
  ADD_SIZE: 'Add Size',
  CATEGORY: 'Category',
  PRODUCT_DETAILS: 'Product Details',
  USER_NAVIGATOR: 'Manage Users',
  USERS: 'Users',
  ALL_USERS: 'All Users',
  MANAGE_USER: 'Manage User',
  CHANGE_PASSWORD: 'Change Password',
};
