export default {
  LOGIN: 'Login',
  REGISTER: 'Register',
  ADMIN_NAVIGATOR: 'AdminNavigator',
  DASHBOARD: 'Dashboard',
  PRODUCT_NAVIGATOR: 'Products',
  PRODUCTS: 'Products Screen',
  ADD_NEW_PRODUCT: 'Add New Product',
  UPDATE_PRODUCT: 'Update Product',
  ALL_PRODUCTS: 'All Products',
  ADD_STOCK: 'Add Stock',
  ADJUST_STOCK: 'Adjust Stock',
  ADD_SIZE: 'Add Size',
  CATEGORY: 'Category',
  PRODUCT_DETAILS: 'Product Details',
  USER_NAVIGATOR: 'Manage Users',
  USERS: 'Users',
  ALL_USERS: 'All Users',
  ADD_NEW_USER: 'Add New User',
  MANAGE_USER: 'Manage User',
  CHANGE_PASSWORD: 'Change Password',
  PENDING_APPROVALS: 'Pending Approvals',
  ORDER_NAVIGATOR: 'Order Navigator',
  ORDERS: 'Orders Page',
  ALL_ORDERS: 'All Orders',
  VIEW_ORDER: 'View Order',
  PENDING_ORDERS: 'Pending Orders',
  VIEW_COMMISION_RECORD: 'View Commision Record',
  //App user routes
  HOME: 'Home',
  ORDERS: 'Orders',
  SEARCH: 'Search',
  PROFILE: 'Profile',
  //App user product routes
  USER_PRODUCT_NAVIGATOR: 'User Product Navigator',
  VIEW_PRODUCT: 'View Product',
  CART: 'Cart',
  //App user order routes
  USER_ORDER_NAVIGATOR: 'User Order Navigator',
  USER_ORDERS: 'User Orders',
  VIEW_ORDER_DETAILS: 'View Order Details',
  //App user search routes
  SEARCH: 'Search',
  USER_SEARCH_NAVIGATOR: 'User Search Navigator',
  //App profile routes
  PROFILE_NAVIGATOR: 'Profile Navigator',
  PROFILE: 'Profile',
  UPDATE_USER_PROFILE: 'Update User Profile',
  CHANGE_USER_PASSWORD: 'Change User Password',
};
